Fix an annotation error detected by mypy
mypy --ignore-missing-imports eyegrade/*.py eyegrade/*/*.py tests/*.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib

eyegrade/create/parser.py:137: error: Argument 1 to "_parse_tree" has incompatible type "Document"; expected "Element"  [arg-type]

Found 1 error in 1 file (checked 52 source files)